fix: disable bypass_platform_safety_checks_on_user_schedule_enabled when hotpatching_enabled is true
Apparently, this additional limitation is not well documented,
but the Azure platform is explicit about it:

Error: creating Windows Virtual Machine (...) performing CreateOrUpdate:
unexpected status 400 (400 Bad Request) with error: InvalidParameter:
  Hotpatch updates require platform safety checks.
  The 'BypassPlatformSafetyChecksOnUserSchedule' flag must be
  set to false to enable hotpatching.

Signed-off-by: Mateusz Łoskot <mateusz@loskot.net>